"""Property-based tests for TaskScheduler.

**Feature: automated-daily-logging, Property 11: Platform-specific commands are syntactically correct**
**Validates: Requirements 5.4, 5.5**
"""

import pytest
import re
from unittest.mock import Mock, patch, MagicMock
from hypothesis import given, strategies as st, settings, assume

from talkbut.scheduling.task_scheduler import TaskScheduler


# Strategy for generating valid time strings in HH:MM format
@st.composite
def valid_time_string(draw):
    """Generate valid time strings in HH:MM format."""
    hour = draw(st.integers(min_value=0, max_value=23))
    minute = draw(st.integers(min_value=0, max_value=59))
    return f"{hour:02d}:{minute:02d}"


# Strategy for generating valid command strings
@st.composite
def valid_command_string(draw):
    """Generate valid command strings for Windows Task Scheduler."""
    # Generate realistic command paths and arguments
    commands = [
        "C:\\Python\\python.exe C:\\path\\to\\script.py",
        "C:\\Program Files\\TalkBut\\talkbut.exe log",
        "python -m talkbut.cli.main log",
        "C:\\Users\\user\\AppData\\Local\\Programs\\Python\\python.exe -m talkbut log --author user",
    ]
    return draw(st.sampled_from(commands))


def is_valid_schtasks_command(command_args: list) -> bool:
    """
    Validate that a schtasks command has correct syntax.
    
    A valid schtasks /Create command should have:
    - /Create flag
    - /SC DAILY (schedule type)
    - /TN <task_name> (task name)
    - /TR <command> (task to run)
    - /ST <time> (start time in HH:MM format)
    - /F (force flag)
    """
    if not isinstance(command_args, list):
        return False
    
    # Must start with schtasks
    if not command_args or command_args[0] != "schtasks":
        return False
    
    # Must have /Create flag
    if "/Create" not in command_args:
        return False
    
    # Must have /SC DAILY
    try:
        sc_index = command_args.index("/SC")
        if sc_index + 1 >= len(command_args) or command_args[sc_index + 1] != "DAILY":
            return False
    except (ValueError, IndexError):
        return False
    
    # Must have /TN with a task name
    try:
        tn_index = command_args.index("/TN")
        if tn_index + 1 >= len(command_args) or not command_args[tn_index + 1]:
            return False
    except (ValueError, IndexError):
        return False
    
    # Must have /TR with a command
    try:
        tr_index = command_args.index("/TR")
        if tr_index + 1 >= len(command_args) or not command_args[tr_index + 1]:
            return False
    except (ValueError, IndexError):
        return False
    
    # Must have /ST with time in HH:MM format
    try:
        st_index = command_args.index("/ST")
        if st_index + 1 >= len(command_args):
            return False
        time_str = command_args[st_index + 1]
        # Validate HH:MM format
        if not re.match(r"^\d{2}:\d{2}$", time_str):
            return False
        hour, minute = map(int, time_str.split(":"))
        if not (0 <= hour <= 23 and 0 <= minute <= 59):
            return False
    except (ValueError, IndexError):
        return False
    
    # Must have /F flag
    if "/F" not in command_args:
        return False
    
    return True


class TestTaskSchedulerProperties:
    """Property-based tests for TaskScheduler."""
    
    @given(time=valid_time_string(), command=valid_command_string())
    @settings(max_examples=100, deadline=None)
    def test_property_schtasks_commands_are_syntactically_correct(self, time, command):
        """
        Property 11: Platform-specific commands are syntactically correct.
        
        For any valid time and command, the schtasks command generated by TaskScheduler
        should be syntactically correct according to Windows Task Scheduler syntax rules.
        
        **Feature: automated-daily-logging, Property 11: Platform-specific commands are syntactically correct**
        **Validates: Requirements 5.4, 5.5**
        """
        scheduler = TaskScheduler()
        
        # Mock subprocess to capture the schtasks command
        captured_command = None
        
        def mock_run(*args, **kwargs):
            """Mock run to capture the command."""
            nonlocal captured_command
            
            # Capture the command if it's a create operation
            if args and len(args) > 0:
                cmd = args[0]
                if isinstance(cmd, list) and "/Create" in cmd:
                    captured_command = cmd
            
            # Mock successful execution
            mock_result = MagicMock()
            mock_result.returncode = 0
            mock_result.stdout = ""
            mock_result.stderr = ""
            return mock_result
        
        with patch('subprocess.run', side_effect=mock_run):
            # Create the task
            result = scheduler.create_task(time, command)
            
            # Verify operation succeeded
            assert result is True, f"create_task failed for time={time}, command={command}"
            
            # Property: The generated schtasks command should be syntactically correct
            assert captured_command is not None, \
                "No schtasks command was captured"
            
            assert is_valid_schtasks_command(captured_command), \
                f"Generated schtasks command is not syntactically correct: {captured_command}"
    
    @given(time=valid_time_string(), command=valid_command_string())
    @settings(max_examples=100, deadline=None)
    def test_property_schtasks_time_matches_input(self, time, command):
        """
        Property 11: Platform-specific commands are syntactically correct.
        
        For any valid time, the schtasks command should have a /ST parameter
        that matches the input time exactly.
        
        **Feature: automated-daily-logging, Property 11: Platform-specific commands are syntactically correct**
        **Validates: Requirements 5.4, 5.5**
        """
        scheduler = TaskScheduler()
        
        # Mock subprocess to capture the schtasks command
        captured_command = None
        
        def mock_run(*args, **kwargs):
            """Mock run to capture the command."""
            nonlocal captured_command
            
            if args and len(args) > 0:
                cmd = args[0]
                if isinstance(cmd, list) and "/Create" in cmd:
                    captured_command = cmd
            
            mock_result = MagicMock()
            mock_result.returncode = 0
            mock_result.stdout = ""
            mock_result.stderr = ""
            return mock_result
        
        with patch('subprocess.run', side_effect=mock_run):
            # Create the task
            result = scheduler.create_task(time, command)
            
            # Verify operation succeeded
            assert result is True, f"create_task failed for time={time}"
            
            # Property: The /ST parameter should match the input time
            assert captured_command is not None, "No schtasks command was captured"
            
            try:
                st_index = captured_command.index("/ST")
                captured_time = captured_command[st_index + 1]
                
                assert captured_time == time, \
                    f"Captured time '{captured_time}' does not match input time '{time}'"
            except (ValueError, IndexError):
                pytest.fail(f"Could not find /ST parameter in command: {captured_command}")
    
    @given(time=valid_time_string(), command=valid_command_string())
    @settings(max_examples=100, deadline=None)
    def test_property_schtasks_daily_schedule_format(self, time, command):
        """
        Property 11: Platform-specific commands are syntactically correct.
        
        For any valid time, the schtasks command should use the DAILY schedule type
        (/SC DAILY).
        
        **Feature: automated-daily-logging, Property 11: Platform-specific commands are syntactically correct**
        **Validates: Requirements 5.4, 5.5**
        """
        scheduler = TaskScheduler()
        
        # Mock subprocess to capture the schtasks command
        captured_command = None
        
        def mock_run(*args, **kwargs):
            """Mock run to capture the command."""
            nonlocal captured_command
            
            if args and len(args) > 0:
                cmd = args[0]
                if isinstance(cmd, list) and "/Create" in cmd:
                    captured_command = cmd
            
            mock_result = MagicMock()
            mock_result.returncode = 0
            mock_result.stdout = ""
            mock_result.stderr = ""
            return mock_result
        
        with patch('subprocess.run', side_effect=mock_run):
            # Create the task
            result = scheduler.create_task(time, command)
            
            # Verify operation succeeded
            assert result is True, f"create_task failed for time={time}"
            
            # Property: The schedule type should be DAILY
            assert captured_command is not None, "No schtasks command was captured"
            
            try:
                sc_index = captured_command.index("/SC")
                schedule_type = captured_command[sc_index + 1]
                
                assert schedule_type == "DAILY", \
                    f"Schedule type should be 'DAILY', got '{schedule_type}'"
            except (ValueError, IndexError):
                pytest.fail(f"Could not find /SC parameter in command: {captured_command}")
    
    @given(time=valid_time_string(), command=valid_command_string())
    @settings(max_examples=100, deadline=None)
    def test_property_schtasks_command_is_preserved(self, time, command):
        """
        Property 11: Platform-specific commands are syntactically correct.
        
        For any valid command, the schtasks command should preserve the command
        exactly as provided in the /TR parameter.
        
        **Feature: automated-daily-logging, Property 11: Platform-specific commands are syntactically correct**
        **Validates: Requirements 5.4, 5.5**
        """
        scheduler = TaskScheduler()
        
        # Mock subprocess to capture the schtasks command
        captured_command = None
        
        def mock_run(*args, **kwargs):
            """Mock run to capture the command."""
            nonlocal captured_command
            
            if args and len(args) > 0:
                cmd = args[0]
                if isinstance(cmd, list) and "/Create" in cmd:
                    captured_command = cmd
            
            mock_result = MagicMock()
            mock_result.returncode = 0
            mock_result.stdout = ""
            mock_result.stderr = ""
            return mock_result
        
        with patch('subprocess.run', side_effect=mock_run):
            # Create the task
            result = scheduler.create_task(time, command)
            
            # Verify operation succeeded
            assert result is True, f"create_task failed for command={command}"
            
            # Property: The command should be preserved in the /TR parameter
            assert captured_command is not None, "No schtasks command was captured"
            
            try:
                tr_index = captured_command.index("/TR")
                captured_cmd = captured_command[tr_index + 1]
                
                assert captured_cmd == command, \
                    f"Captured command '{captured_cmd}' does not match input command '{command}'"
            except (ValueError, IndexError):
                pytest.fail(f"Could not find /TR parameter in command: {captured_command}")
    
    @given(time=valid_time_string(), command=valid_command_string())
    @settings(max_examples=100, deadline=None)
    def test_property_schtasks_task_name_is_consistent(self, time, command):
        """
        Property 11: Platform-specific commands are syntactically correct.
        
        For any valid time and command, the schtasks command should use the
        consistent task name defined in TaskScheduler.TASK_NAME.
        
        **Feature: automated-daily-logging, Property 11: Platform-specific commands are syntactically correct**
        **Validates: Requirements 5.4, 5.5**
        """
        scheduler = TaskScheduler()
        
        # Mock subprocess to capture the schtasks command
        captured_command = None
        
        def mock_run(*args, **kwargs):
            """Mock run to capture the command."""
            nonlocal captured_command
            
            if args and len(args) > 0:
                cmd = args[0]
                if isinstance(cmd, list) and "/Create" in cmd:
                    captured_command = cmd
            
            mock_result = MagicMock()
            mock_result.returncode = 0
            mock_result.stdout = ""
            mock_result.stderr = ""
            return mock_result
        
        with patch('subprocess.run', side_effect=mock_run):
            # Create the task
            result = scheduler.create_task(time, command)
            
            # Verify operation succeeded
            assert result is True, f"create_task failed for time={time}"
            
            # Property: The task name should match TASK_NAME
            assert captured_command is not None, "No schtasks command was captured"
            
            try:
                tn_index = captured_command.index("/TN")
                task_name = captured_command[tn_index + 1]
                
                assert task_name == scheduler.TASK_NAME, \
                    f"Task name '{task_name}' does not match expected '{scheduler.TASK_NAME}'"
            except (ValueError, IndexError):
                pytest.fail(f"Could not find /TN parameter in command: {captured_command}")
    
    @given(time=valid_time_string(), command=valid_command_string())
    @settings(max_examples=100, deadline=None)
    def test_property_schtasks_force_flag_is_present(self, time, command):
        """
        Property 11: Platform-specific commands are syntactically correct.
        
        For any valid time and command, the schtasks command should include the
        /F flag to force overwrite existing tasks.
        
        **Feature: automated-daily-logging, Property 11: Platform-specific commands are syntactically correct**
        **Validates: Requirements 5.4, 5.5**
        """
        scheduler = TaskScheduler()
        
        # Mock subprocess to capture the schtasks command
        captured_command = None
        
        def mock_run(*args, **kwargs):
            """Mock run to capture the command."""
            nonlocal captured_command
            
            if args and len(args) > 0:
                cmd = args[0]
                if isinstance(cmd, list) and "/Create" in cmd:
                    captured_command = cmd
            
            mock_result = MagicMock()
            mock_result.returncode = 0
            mock_result.stdout = ""
            mock_result.stderr = ""
            return mock_result
        
        with patch('subprocess.run', side_effect=mock_run):
            # Create the task
            result = scheduler.create_task(time, command)
            
            # Verify operation succeeded
            assert result is True, f"create_task failed for time={time}"
            
            # Property: The /F flag should be present
            assert captured_command is not None, "No schtasks command was captured"
            
            assert "/F" in captured_command, \
                f"Force flag /F not found in command: {captured_command}"
